version: "2"

services:
  server:
    build: .
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    environment:
      PORT: "8080"
      DB_HOST: "database"
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    links:
      - database
    command: ["npm", "start"]
  database:
    image: postgres:latest
    ports:
      - 11543:5432
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"

volumes:
  database-data: {}
