

@hostname = localhost
@port = 8081
@host = {{hostname}}:{{port}}


##

// Create Employe
POST /api/v1/employe/ HTTP/1.1
Host: {{host}}

{
    "name": "test 1",
    "firstName": "first name",
    "department": "IT"
}


### 


// get all Employe
GET /api/v1/client/ HTTP/1.1
Host: {{host}}

